### ISSUE TITLE
如何复现

### ISSUE THREAD

**Issue by Kubby-ym** [jackchen0120/vueDataV#10]
请问您这个项目有具体的实现过程吗？我想从零复现一下，或者您给推荐一本学习的书、网站或其他可能用于学习的东西。

**Comment by jackchen0120** [comment]
> 请问您这个项目有具体的实现过程吗？我想从零复现一下，或者您给推荐一本学习的书、网站或其他可能用于学习的东西。

你好，有简易教程分上下两篇，看看是否对你有帮助 
https://juejin.cn/post/6844904158181457933
https://juejin.cn/post/6845166890449371149

**Comment by jackchen0120** [comment]
> 请问您这个项目有具体的实现过程吗？我想从零复现一下，或者您给推荐一本学习的书、网站或其他可能用于学习的东西。

如遇到技术问题，可以加我微信：lazycode520，拉你进技术群，一起交流一起学习
