### ISSUE TITLE
省份坐标信息为什么是乱码？

### ISSUE THREAD

**Issue by cylmemory** [jackchen0120/vueDataV#25]
位置：Brand.vue,china.js 坐标信息coordinates乱码

详情：
```
{
        id: "710000",
        geometry: {
          type: "MultiPolygon",
          coordinates: [
            [
              "@@°Ü¯Û",
              "@@ƛĴÕƊÉɼģºðʀ\\ƎsÆNŌÔĚänÜƤɊĂǀĆĴĤǊŨxĚĮǂƺòƌâÔ®ĮXŦţƸZûÐƕƑGđ¨ĭMó·ęcëƝɉlÝƯֹÅŃ^Ó·śŃǋƏďíåɛGɉ¿IċããF¥ĘWǬÏĶñÄ",
              "@@\\p|WoYG¿¥Ij@",
              "@@¡@V^RqBbAnTXeQr©C",
              "@@ÆEEkWqë I"
            ]
          ],
          encodeOffsets: [
            [
              [122886, 24033],
              [123335, 22980],
              [122375, 24193],
              [122518, 24117],
              [124427, 22618]
            ]
          ]
        },
        properties: { cp: [121.509062, 25.044332], name: "台湾", childNum: 5 }
      }
```

**Comment by jackchen0120** [comment]
> 位置：Brand.vue,china.js 坐标信息coordinates乱码
> 
> 详情：
> 
> ```
> {
>         id: "710000",
>         geometry: {
>           type: "MultiPolygon",
>           coordinates: [
>             [
>               "@@°Ü¯Û",
>               "@@ƛĴÕƊÉɼģºðʀ\\ƎsÆNŌÔĚä�nÜƤɊĂǀĆĴ�ĤǊŨxĚĮǂƺòƌ��âÔ®ĮXŦţƸ�ZûÐ�ƕƑGđ¨ĭMó·ęcëƝɉlÝƯֹÅŃ^Ó·��śŃǋƏď�íåɛGɉ�¿Iċã�ãF¥ĘWǬÏĶñÄ",
>               "@@\\p|WoYG¿¥I�j@�",
>               "@@�¡�@��V^Rq�B�bA�nTXe���Qr�©C",
>               "@@ÆEE��kWqë I�"
>             ]
>           ],
>           encodeOffsets: [
>             [
>               [122886, 24033],
>               [123335, 22980],
>               [122375, 24193],
>               [122518, 24117],
>               [124427, 22618]
>             ]
>           ]
>         },
>         properties: { cp: [121.509062, 25.044332], name: "台湾", childNum: 5 }
>       }
> ```

源文件就是乱码，不用在意，能正常使用就行

**Comment by jackchen0120** [comment]
源文件就是乱码，不用在意，能正常使用就行

**Comment by jackchen0120** [comment]
源文件就是乱码，不用在意，能正常使用就行
