### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by zhujianxiong** [jackchen0120/vueDataV#26]
![image](https://user-images.githubusercontent.com/45658422/147733177-87186766-136d-4e7c-a8f2-289f9975289c.png)

1.文字没有设配；
2.底部下方留白；

**Comment by zhujianxiong** [comment]
![image](https://user-images.githubusercontent.com/45658422/147733261-d1606f9c-76d0-474b-bebe-c25ab7a8c294.png)

**Comment by jackchen0120** [comment]
感谢反馈，已修复了
